{
	"version": 1559441825,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/amigo-sheet0.png",
		"images/botaodeplya-sheet0.png",
		"images/peiamigo-sheet0.png",
		"images/cima-sheet0.png",
		"images/lado1-sheet0.png",
		"images/lado2-sheet0.png",
		"images/baixo-sheet0.png",
		"images/sprite-sheet0.png",
		"images/inimigo-sheet0.png",
		"images/peuinimigo-sheet0.png",
		"images/hp-sheet0.png",
		"images/hp3-sheet0.png",
		"images/valorhp.png",
		"images/powerupss-sheet0.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}